### ISSUE TITLE
how do i get utf8 decompiled code?

### ISSUE THREAD

**Issue by MoaMoa90** [serfend/pydumpck#21]
hi, i just tried this amazing module and for most of compiled files with pyinstaller is working great!

but i would like to let pydumpck decompile code based on utf8, due to strings like this 

\xeb\x9d\xbc\xec\x9d\xb4\xec\x84\xa0\xec\x8a\xa4 \xeb\xa7\x8c\xeb\xa3\x8c! 

how can i do that?

**Comment by serfend** [comment]
supported in [1.15.17](https://github.com/serfend/pydumpck/releases/tag/1.15.17)
