### ISSUE TITLE
'pydumpck' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by BESTRAPER** [serfend/pydumpck#29]
when i try to execute a command it says 'pydumpck' is not recognized as an internal or external command,
operable program or batch file.

**Comment by serfend** [comment]
run `pip show pydumpck`,check if you get following output.

Name: pydumpck
Version: 1.15.20
Summary: pydumpck is a multi-threads tool for decompile exe,elf,pyz,pyc packed by python which is base on pycdc and uncompyle6.sometimes its py-file result not exactly right ,maybe could use uncompyle6.
Home-page: https://github.com/serfend/pydumpck
Author: serfend
Author-email: serfend@foxmail.com
License: MIT Licence
Location: c:\users\sf\appdata\local\programs\python\python310\lib\site-packages\pydumpck-1.15.20-py3.10.egg
Requires: pyinstaller, sgtpyutils, tinyaes, uncompyle6, xdis
Required-by:
